"""
Django settings for mysite project.

settings.py zawiera parametry i konfigurację projektu oraz ustawienia domyślne;

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/


- - - - - - - - -

For the full list of settings and their values, see /
Wszystkie ustawienia i ich domyślne wartości można znaleźć pod adresem
https://docs.djangoproject.com/en/2.0/ref/settings/

- - - - - - - - -



"""




import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qp9cg882yolit#v)^q82w96r=qzq(!pzb(g$^3hx*kii1y*3nx'



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG to wartość typu boolean ; w zależności od ustawienia włącza bądź wyłącza tryb
# debugowania projektu. Jeśli jest ustawione na True , Django wyświetla szczegółowe
# strony błędów, gdy aplikacja zgłosi nieobsłużony wyjątek. Należy pamiętać, aby po
# przejściu do środowiska produkcyjnego ustawić je na False . Nigdy nie wdrażaj
# witryny do produkcji z włączonym ustawieniem DEBUG , ponieważ może to doprowadzić
# do ujawnienia poufnych danych związanych z projektem.



ALLOWED_HOSTS = []
# Ustawienie ALLOWED_HOSTS nie jest stosowane przy włączonym trybie debugowania
# albo gdy są uruchamiane testy. Po przeniesieniu witryny do produkcji i ustawieniu
# DEBUG na False , aby umożliwić obsługę witryny Django, trzeba dodać do tego
# ustawienia domenę (hosta).




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog.apps.BlogConfig',
]
# INSTALLED_APPS to ustawienie, które trzeba wyedytować dla wszystkich projektów.
# Informuje ono Django o tym, które aplikacje są aktywne dla tej witryny. Domyślnie
# Django włącza następujące aplikacje:
# -  django.contrib.admin : witryna administracyjna;
# -  django.contrib.auth : framework uwierzytelniania;
# -  django.contrib.contenttypes : framework obsługi typów zawartości;
# -  rtfg
# -  django.contrib.messages : framework obsługi komunikatów;
# -  django.contrib.staticfiles : framework zarządzania statycznymi plikami.



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# MIDDLEWARE to lista zawierająca oprogramowanie middleware do uruchomienia.



ROOT_URLCONF = 'mysite.urls'
# ROOT_URLCONF wskazuje moduł Pythona, w którym zdefiniowano wzorce URL aplikacji.



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'mysite.wsgi.application'




# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
# DATABASES to słownik zawierający ustawienia wszystkich baz danych, które będą
# używane w projekcie. W projekcie zawsze musi być domyślna baza danych.
# W domyślnej konfiguracji używana jest baza danych SQLite3.




# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/



LANGUAGE_CODE = 'en-us'
# LANGUAGE_CODE definiuje kod domyślnego języka dla witryny Django.



TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
# Ustawienie USE_TZ informuje Django, aby aktywował (dezaktywował) obsługę
# stref czasowych. Django zapewnia obsługę typu datetime uwzględniającego strefy
# czasowe. Po utworzeniu nowego projektu za pomocą polecenia zarządzającego
# startproject opcja ta jest ustawiona na True.



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
